isaacsim.replicator.agent:
  version: 0.7.0
  global:
    seed: 42
    simulation_length: 300
  scene:
    asset_path:
  sensor:
    camera_num: 0
  character:
    num: 3
    command_file: idle_command.txt
  robot:
    nova_carter_num: 0
    iw_hub_num: 0
    write_data: false
